    - name: Copy install script
      ansible.builtin.copy:
        src: awx-manifest.yaml
        dest: awx-manifest.yaml

    - name: Copy install script
      ansible.builtin.copy:
        src: kustomization.yaml
        dest: kustomization.yaml

    - name: awx
      ansible.builtin.command: kubectl apply -k .
