---
# ## ---------------------------------- ##
- name: GET SURVEY PROVIDED TARGETS
  hosts: localhost
  gather_facts: False
  tasks:
  # Add locally provided hosts to a group
    - name: Adding list of hosts to group
      add_host:
        name: "{{ item }}"
        group: survey_hosts
      loop: "{{ run_hosts.split('\n') }}"
      # Running this on the Ansible contoller only:
      delegate_to: localhost
      run_once: True

# ## ---------------------------------- ##
- name: Copy File
  hosts: survey_hosts
  gather_facts: False
  
  vars:
    #source: 'temp/'
    #target: 'C:\Temp\'
    #ansible_user: '{{ domain_user }}@{{ admin_domain }}'

  tasks:
    - name: Upgrade all packages
      ansible.builtin.import_tasks:
        file: tasks/update_rocky.yml
    
    - name: Task name
      stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: k3s_exist

    - name: Copy install script
      ansible.builtin.copy:
        src: install_k3s.sh
        dest: install_k3s.sh
      when: not k3s_exist.stat.exists
    
    - name: Changing perm of "install_k3s.sh", adding "+x"
      file: dest=install_k3s.sh mode=a+x
      when: not k3s_exist.stat.exists

    - name: install k3s
      ansible.builtin.command: ./install_k3s.sh
      become: true
      become_user: rocky
      when: not k3s_exist.stat.exists

    - name: Copy kubeconfig
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: .kube/config
        remote_src: yes
      become: true
      become_user: rocky